import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import { useSearchParams} from 'next/navigation'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Counter() {

    const [number, setNumber] = useState(0);
    const SearchParams = useSearchParams();
    const isUser = SearchParams.get('username');
    const router = useRouter();

    useEffect(() => {
        if(!isUser) {
            router.push(
                '/'
            )
        }
    }, [isUser])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            COUNTER PAGE &nbsp;
            <code className={styles.code}>Welcome {isUser} </code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Best Counter By{' Patrick Hui '}

            </a>
          </div>
        </div>

        <div className={styles.center}>

          <h1>Best Counter</h1> 

        </div>

        <div className={styles.grid}>
         <h2>
            The number is:
         </h2>
         <p>
            {number}
         </p>
         <button onClick={() => setNumber(number + 1)}>Increment</button>
         <button onClick={() => setNumber(number - 1)}>Decrement</button>
        </div>
      </main>
    </>
  )
}
